---
name: Documentation Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/docs-lint.yaml'
      - 'docs/**'

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: .go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint

  save-artifacts-on-fail:
    if: ${{ needs.docs-lint.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml
